# -*- coding: utf-8 -*-
"""DataMining_Hallucinations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VjtqxQlxpI2EA16ER3eEJXC6Olf7JifK

## **Cloning Repo**
"""

!git clone https://github.com/D2I-ai/eigenscore.git

!python hallucination_evaluation_integrated.py

"""### **Install Dependencies**"""

!pip install -q transformers torch scipy scikit-learn matplotlib

"""## **Imports**"""

import os
import json
import numpy as np
import matplotlib.pyplot as plt
import torch
from typing import Dict, List

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.linalg import eigh
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, roc_auc_score

"""## **Load CoQA Dataset**"""

def load_coqa(data_path, max_samples=200):
    with open(data_path, 'r') as f:
        data = json.load(f)['data']

    samples = []
    for story in data:
        for q, a in zip(story['questions'], story['answers']):
            samples.append({
                'qa': f"Q: {q['input_text']} A: {a['input_text']}"
            })
            if len(samples) >= max_samples:
                return samples
    return samples

coqa_path = "eigenscore/data/datasets/coqa-dev-v1.0.json"

samples = load_coqa(coqa_path)
texts = [s['qa'] for s in samples]

print("Loaded samples:", len(texts))
print(texts[:2])

"""## **Load RoBERTa-MNLI Model**"""

device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained("roberta-large-mnli")
model = AutoModelForSequenceClassification.from_pretrained("roberta-large-mnli").to(device)
model.eval()

print("Model loaded on:", device)

"""## **Get Model Outputs**"""

def get_logits(texts):
    logits_list = []
    with torch.no_grad():
        for text in texts:
            inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(device)
            outputs = model(**inputs)
            logits_list.append(outputs.logits.cpu().numpy().flatten())
    return np.array(logits_list)

logits = get_logits(texts)
print("Logits shape:", logits.shape)

"""## **Softmax + Mapping**"""

def softmax(x):
    e = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e / np.sum(e, axis=1, keepdims=True)

probs = softmax(logits)

# MNLI mapping
hallucination_prob = probs[:, 1] + probs[:, 2]

# Threshold tuning
threshold = 0.6
predictions = (hallucination_prob > threshold).astype(int)

print("Sample probs:", hallucination_prob[:5])
print("Predictions:", predictions[:5])

"""## **Labels (TEMP / DEMO)**"""

labels = np.array([i % 2 for i in range(len(texts))])

print("Label distribution:", np.bincount(labels))

"""## **Metrics**"""

accuracy = accuracy_score(labels, predictions)
precision = precision_score(labels, predictions, zero_division=0)
recall = recall_score(labels, predictions, zero_division=0)
f1 = f1_score(labels, predictions, zero_division=0)
auc_score = roc_auc_score(labels, hallucination_prob)

print("\n=== METRICS ===")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print("AUC      :", auc_score)

"""## **ROC Curve**"""

fpr, tpr, _ = roc_curve(labels, hallucination_prob)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc_score:.4f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("ROC Curve")
plt.legend()
plt.grid()
plt.show()

"""## **Eigenvector Hallucination Score**"""

def eigen_score(logits):
    cov = np.cov(logits.T)
    eigenvalues = np.linalg.eigvals(cov)
    eigenvalues = np.abs(eigenvalues)

    eigenvalues /= np.sum(eigenvalues)
    entropy = -np.sum(eigenvalues * np.log(eigenvalues + 1e-10))
    max_entropy = np.log(len(eigenvalues))

    return entropy / max_entropy

score = eigen_score(logits)

print("Eigen Hallucination Score:", score)

"""## **Final Summary**"""

print("\n===== FINAL SUMMARY =====")
print("Accuracy:", accuracy)
print("AUC:", auc_score)
print("Eigen Score:", score)



"""# **Model Optimization Increasing the Accuracy**

**Install Dependencies**
"""

!pip install transformers torch scipy scikit-learn matplotlib -q

"""**Imports**"""

import os
import json
import re
import numpy as np
import matplotlib.pyplot as plt
from typing import Dict, List, Tuple
import warnings
warnings.filterwarnings('ignore')

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.linalg import eigh
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, roc_auc_score
import torch

"""**Dataset Path Check**"""

coqa_path = "/content/eigenscore/data/datasets/coqa-dev-v1.0.json"

print("File exists:", os.path.exists(coqa_path))

"""**Text Preprocessor** Preprocessing"""

class TextPreprocessor:
    @staticmethod
    def preprocess(text: str) -> str:
        text = str(text).lower()
        text = re.sub(r'\s+', ' ', text).strip()
        text = re.sub(r'([.,:;!?\'"()])', r' \1 ', text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text

"""**Threshold Optimizer**"""

class ThresholdOptimizer:
    @staticmethod
    def find_optimal_threshold(y_true, y_proba):
        thresholds = np.linspace(0, 1, 101)
        best_thresh, best_f1 = 0.5, 0

        for t in thresholds:
            preds = (y_proba >= t).astype(int)
            score = f1_score(y_true, preds, zero_division=0)
            if score > best_f1:
                best_f1 = score
                best_thresh = t

        return best_thresh, best_f1

"""**Load Dataset**"""

def load_coqa(data_path, max_samples=50):
    with open(data_path, 'r') as f:
        data = json.load(f)['data']

    samples = []

    for story in data:
        for q, a in zip(story['questions'], story['answers']):
            samples.append({
                'qa': f"Q: {q['input_text']} A: {a['input_text']}"
            })

            if len(samples) >= max_samples:
                return samples

    return samples

samples = load_coqa(coqa_path)
texts = [s['qa'] for s in samples]

print("Loaded samples:", len(texts))

"""**Create Labels (TEMP / DEMO)**"""

# Replace this later with real labels
true_labels = np.array([i % 2 for i in range(len(texts))])

"""**Load Model**"""

device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained("roberta-large-mnli")
model = AutoModelForSequenceClassification.from_pretrained("roberta-large-mnli").to(device)
model.eval()

print("Model loaded on:", device)

"""**Generate Embeddings**"""

def get_embeddings(texts):
    embeddings = []
    pre = TextPreprocessor()

    with torch.no_grad():
        for t in texts:
            t = pre.preprocess(t)
            inputs = tokenizer(t, return_tensors="pt", truncation=True, max_length=512).to(device)
            outputs = model(**inputs)
            logits = outputs.logits.cpu().numpy().flatten()
            embeddings.append(logits)

    return np.array(embeddings)

embeddings = get_embeddings(texts)
print("Embeddings shape:", embeddings.shape)

"""**Convert to Probabilities**"""

def softmax(x):
    exp = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp / np.sum(exp, axis=1, keepdims=True)

probs = softmax(embeddings)

# hallucination = neutral + contradiction
hallucination_proba = probs[:,1] + probs[:,2]

"""**Eigen Score**"""

def eigen_score(embeddings):
    cov = np.cov(embeddings.T)
    eigvals, _ = eigh(cov)
    eigvals = np.abs(eigvals)

    eigvals /= np.sum(eigvals)
    entropy = -np.sum(eigvals * np.log(eigvals + 1e-10))
    return entropy / np.log(len(eigvals))

e_score = eigen_score(embeddings)
e_scores = np.ones(len(texts)) * e_score

"""**Hybrid Score**"""

alpha = 0.6
hybrid_scores = alpha * hallucination_proba + (1 - alpha) * e_scores

"""**Find Best Threshold**"""

opt = ThresholdOptimizer()
best_thresh, best_f1 = opt.find_optimal_threshold(true_labels, hybrid_scores)

print("Best Threshold:", best_thresh)
print("Best F1:", best_f1)

"""**Final Predictions**"""

preds = (hybrid_scores >= best_thresh).astype(int)

acc = accuracy_score(true_labels, preds)
prec = precision_score(true_labels, preds, zero_division=0)
rec = recall_score(true_labels, preds, zero_division=0)
f1 = f1_score(true_labels, preds, zero_division=0)
auc = roc_auc_score(true_labels, hybrid_scores)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)
print("F1:", f1)
print("AUC:", auc)

"""**ROC Curve**"""

fpr, tpr, _ = roc_curve(true_labels, hybrid_scores)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc:.3f}")
plt.plot([0,1],[0,1],'--')
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("ROC Curve")
plt.legend()
plt.show()

